defmodule ElixirLokaliseApi.Model.Key do
  defstruct key_id: nil,
            created_at: nil,
            created_at_timestamp: nil,
            key_name: %{},
            filenames: %{},
            description: nil,
            platforms: [],
            tags: [],
            comments: %{},
            screenshots: %{},
            translations: %{},
            is_plural: nil,
            plural_name: nil,
            is_hidden: nil,
            is_archived: nil,
            context: nil,
            base_words: nil,
            char_limit: nil,
            custom_attributes: nil,
            modified_at: nil,
            modified_at_timestamp: nil,
            translations_modified_at: nil,
            translations_modified_at_timestamp: nil
end
