defmodule ElixirLokaliseApi.Model.Task do
  @moduledoc false
  defstruct task_id: nil,
            title: nil,
            description: nil,
            status: nil,
            progress: nil,
            due_date: nil,
            due_date_timestamp: nil,
            keys_count: nil,
            words_count: nil,
            created_at: nil,
            created_at_timestamp: nil,
            created_by: nil,
            created_by_email: nil,
            can_be_parent: nil,
            task_type: nil,
            parent_task_id: nil,
            closing_tags: [],
            do_lock_translations: nil,
            languages: %{},
            source_language_iso: nil,
            auto_close_languages: nil,
            auto_close_task: nil,
            auto_close_items: nil,
            completed_at: nil,
            completed_at_timestamp: nil,
            completed_by: nil,
            completed_by_email: nil,
            custom_translation_status_ids: []
end
